-- Eliminar la tabla si ya existe
DROP TABLE IF EXISTS application_train;

-- Crear la tabla application_train
CREATE TABLE IF NOT EXISTS application_train
(
    sk_id_curr integer NOT NULL,
    target integer,
    name_contract_type character varying(50) COLLATE pg_catalog."default",
    code_gender character varying(10) COLLATE pg_catalog."default",
    flag_own_car character(1) COLLATE pg_catalog."default",
    flag_own_realty character(1) COLLATE pg_catalog."default",
    cnt_children integer,
    amt_income_total numeric(15,2),
    amt_credit numeric(15,2),
    amt_annuity numeric(15,2),
    amt_goods_price numeric(15,2),
    name_type_suite character varying(50) COLLATE pg_catalog."default",
    name_income_type character varying(50) COLLATE pg_catalog."default",
    name_education_type character varying(50) COLLATE pg_catalog."default",
    name_family_status character varying(50) COLLATE pg_catalog."default",
    name_housing_type character varying(50) COLLATE pg_catalog."default",
    region_population_relative numeric(10,8),
    days_birth integer,
    days_employed integer,
    days_registration numeric(15,2),
    days_id_publish integer,
    own_car_age double precision,
    flag_mobil integer,
    flag_emp_phone integer,
    flag_work_phone integer,
    flag_cont_mobile integer,
    flag_phone integer,
    flag_email integer,
    occupation_type character varying(50) COLLATE pg_catalog."default",
    cnt_fam_members numeric(15,2),
    region_rating_client integer,
    region_rating_client_w_city integer,
    weekday_appr_process_start character varying(20) COLLATE pg_catalog."default",
    hour_appr_process_start integer,
    reg_region_not_live_region integer,
    reg_region_not_work_region integer,
    live_region_not_work_region integer,
    reg_city_not_live_city integer,
    reg_city_not_work_city integer,
    live_city_not_work_city integer,
    organization_type character varying(50) COLLATE pg_catalog."default",
    ext_source_1 numeric(15,8),
    ext_source_2 numeric(15,8),
    ext_source_3 numeric(15,8),
    apartments_avg numeric(15,8),
    basementarea_avg numeric(15,8),
    years_beginexpluatation_avg numeric(15,8),
    years_build_avg numeric(15,8),
    commonarea_avg numeric(15,8),
    elevators_avg numeric(15,8),
    entrances_avg numeric(15,8),
    floorsmax_avg numeric(15,8),
    floorsmin_avg numeric(15,8),
    landarea_avg numeric(15,8),
    livingapartments_avg numeric(15,8),
    livingarea_avg numeric(15,8),
    nonlivingapartments_avg numeric(15,8),
    nonlivingarea_avg numeric(15,8),
    apartments_mode numeric(15,8),
    basementarea_mode numeric(15,8),
    years_beginexpluatation_mode numeric(15,8),
    years_build_mode numeric(15,8),
    commonarea_mode numeric(15,8),
    elevators_mode numeric(15,8),
    entrances_mode numeric(15,8),
    floorsmax_mode numeric(15,8),
    floorsmin_mode numeric(15,8),
    landarea_mode numeric(15,8),
    livingapartments_mode numeric(15,8),
    livingarea_mode numeric(15,8),
    nonlivingapartments_mode numeric(15,8),
    nonlivingarea_mode numeric(15,8),
    apartments_medi numeric(15,8),
    basementarea_medi numeric(15,8),
    years_beginexpluatation_medi numeric(15,8),
    years_build_medi numeric(15,8),
    commonarea_medi numeric(15,8),
    elevators_medi numeric(15,8),
    entrances_medi numeric(15,8),
    floorsmax_medi numeric(15,8),
    floorsmin_medi numeric(15,8),
    landarea_medi numeric(15,8),
    livingapartments_medi numeric(15,8),
    livingarea_medi numeric(15,8),
    nonlivingapartments_medi numeric(15,8),
    nonlivingarea_medi numeric(15,8),
    fondkapremont_mode character varying(50) COLLATE pg_catalog."default",
    housetype_mode character varying(50) COLLATE pg_catalog."default",
    totalarea_mode numeric(15,8),
    wallsmaterial_mode character varying(50) COLLATE pg_catalog."default",
    emergencystate_mode character varying(50) COLLATE pg_catalog."default",
    obs_30_cnt_social_circle numeric(15,2),
    def_30_cnt_social_circle numeric(15,2),
    obs_60_cnt_social_circle numeric(15,2),
    def_60_cnt_social_circle numeric(15,2),
    days_last_phone_change numeric(15,2),
    flag_document_2 integer,
    flag_document_3 integer,
    flag_document_4 integer,
    flag_document_5 integer,
    flag_document_6 integer,
    flag_document_7 integer,
    flag_document_8 integer,
    flag_document_9 integer,
    flag_document_10 integer,
    flag_document_11 integer,
    flag_document_12 integer,
    flag_document_13 integer,
    flag_document_14 integer,
    flag_document_15 integer,
    flag_document_16 integer,
    flag_document_17 integer,
    flag_document_18 integer,
    flag_document_19 integer,
    flag_document_20 integer,
    flag_document_21 integer,
    amt_req_credit_bureau_hour numeric(15,2),
    amt_req_credit_bureau_day numeric(15,2),
    amt_req_credit_bureau_week numeric(15,2),
    amt_req_credit_bureau_mon numeric(15,2),
    amt_req_credit_bureau_qrt numeric(15,2),
    amt_req_credit_bureau_year numeric(15,2),
    CONSTRAINT pk_app_train PRIMARY KEY (sk_id_curr)
)


SET ROLE postgres;
COPY application_train
FROM '/tmp/application_train_bkp.csv'
DELIMITER ','
CSV HEADER ; 
